#on: [ push ]
#
#permissions:
#  contents: write
#
#jobs:
#  release_ubuntu:
#    runs-on: ubuntu-latest
#    name: A job to say hello
#    steps:
#      - name: Checkout
#        id: checkout
#        uses: actions/checkout@v4
#      - name: build
#        run: |
#          npm ci
#          npm run build
#      - run: |
#          pwd
#          ls -al
#          zip -r dist.zip dist
#      - if: github.ref_type == 'tag'
#        name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: dist.zip
#          draft: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
