on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release_macos:
    runs-on: macos-latest
    name: release macos
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          npm ci
          npm run tauri-build
      - name: 打印目录文件
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './src-tauri/target/release/bundle'
          depth: 2
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./src-tauri/target/release/bundle/macos/*.app
            ./src-tauri/target/release/bundle/dmg/*.dmg
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
