on: [ push ]

permissions:
  contents: write

jobs:
  release_ubuntu:
    runs-on: ubuntu-latest
    name: 打包ubuntu平台
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
#          sudo apt install libglib2.0-dev libgtk-3-dev
          npm ci
          npm run tauri-build
      - name: 打印目录文件
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './src-tauri/target/release/bundle'
#      - run: |
#          pwd
#          ls -al
#          zip -r dist.zip dist
#      - if: github.ref_type == 'tag'
#        name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: dist.zip
#          draft: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
