on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release_macos:
    runs-on: macos-latest
    name: release macos
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          npm ci
          npm run tauri-build
      - name: 打印目录文件
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './src-tauri/target/release/bundle'
          depth: 2
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            ./src-tauri/target/release/bundle/rpm/*.rpm
#            ./src-tauri/target/release/bundle/deb/*.deb
#            ./src-tauri/target/release/bundle/appimage/*.AppImage
#          draft: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
