name: 发布

on:
  push:
    branches:
      - updater

env:
  IS_CI: true

permissions:
  contents: write

jobs:

  Ubuntu:
    name: 发布Ubuntu平台
    runs-on: ubuntu-latest
    steps:
      - name: 添加tauri依赖
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - name: 打包
        run: |
          npm ci
          npm run tauri-build
      - name: 打印文件树
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './src-tauri/target/release/bundle'
          depth: 2
